# Narrator voice with Microsoft neural voices (edge-tts, free, needs internet; the text is
# sent to Microsoft). One request per line, no daily cap. Writes audio/*.mp3 and voice.js.
#   python tts_edge.py [--voice km-KH-PisethNeural] [--rate -10%] [--pitch -6Hz]
#   edge-tts --list-voices | grep km-KH     (Khmer: PisethNeural, SreymomNeural)
import argparse, array, asyncio, json, os, subprocess
import edge_tts
ap = argparse.ArgumentParser(); ap.add_argument('--voice', default='km-KH-PisethNeural'); ap.add_argument('--rate', default='-10%'); ap.add_argument('--pitch', default='-6Hz')
ap.add_argument('--narration', default='narration.json'); ap.add_argument('--out', default='audio'); A = ap.parse_args()
async def gen(text, path):
    if not os.path.exists(path): await edge_tts.Communicate(text, A.voice, rate=A.rate, pitch=A.pitch).save(path)
os.makedirs(A.out, exist_ok=True); out = []
for s in json.load(open(A.narration)):
    lines = []
    for i, l in enumerate(s['lines']):
        say, sub, sub2 = l[0], l[1] or l[0], l[2] if len(l) > 2 else ''
        mp3 = f"{A.out}/{s['scene']}-{i}.mp3"; asyncio.run(gen(say, mp3))
        pcm = subprocess.run(['ffmpeg', '-v', 'error', '-i', mp3, '-ac', '1', '-ar', '24000', '-f', 's16le', '-'], capture_output=True).stdout
        a = array.array('h', pcm); env = [round((sum(x * x for x in a[k * 1000:(k + 1) * 1000]) / 1000) ** .5 / 32768, 3) for k in range(len(a) // 1000)]
        lines.append({'file': mp3, 'dur': round(len(a) / 24000, 3), 'sub': sub, 'sub2': sub2, 'env': env}); print(s['scene'], i, lines[-1]['dur'])
    out.append({'scene': s['scene'], 'lines': lines})
open('voice.js', 'w').write("'use strict';\n// Generated by tts_edge.py: narrator lines, durations (s), 24 fps loudness envelopes.\nconst VOICE = " + json.dumps(out, ensure_ascii=False) + ";\n")
print('total speech', round(sum(l['dur'] for s in out for l in s['lines']), 1), 's')
